name: Cypress Tests

on: [push]

jobs:
  cypress-electron-tests:
    runs-on: ubunt-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.3
        
      - name: Install dependencies
        run: npm install
        
      - name: Run e2e tests
        run: npm cypress run
        
      
